### ISSUE TITLE
导入导出好像都无法用，看能否集成起来

### ISSUE THREAD

**Issue by asreday** [mengshukeji/Luckyexcel#13]
导入导出好像都无法用，看能否集成起来，打包出来后导入文件还是提示LuckyExcel is not defined

**Comment by wubin1989** [comment]
我也遇到同样的问题，有没有解决办法？

**Comment by oy-paddy** [comment]
可以参考这个：https://blog.csdn.net/u014632228/article/details/109738221

**Comment by mengshukeji** [comment]
打包问题已经修复，参考readme
