### ISSUE TITLE
luckyexcel.js 有demo内容，应去除

### ISSUE THREAD

**Issue by mengshukeji** [mengshukeji/Luckyexcel#17]
build把demo的几个dom元素也打进去了
![image](https://user-images.githubusercontent.com/61444807/98499209-d5ebe980-2283-11eb-899e-c812fa5ef1bd.png)

**Comment by oy-paddy** [comment]
他这个demo 是绑定了id，(⊙_⊙) 自己可以修改 src 目录下main.ts文件，然后通过npm run build 会生成新js文件！你可以自己修改逻辑，一开始就加载xlsx资源文件，或者其他逻辑。

**Comment by oy-paddy** [comment]
@mengshukeji **原来是大佬，我错了！我以为是萌新 ORZ**

**Comment by mengshukeji** [comment]
> 他这个demo 是绑定了id，(⊙_⊙) 自己可以修改 src 目录下main.ts文件，然后通过npm run build 会生成新js文件！你可以自己修改逻辑，一开始就加载xlsx资源文件，或者其他逻辑。

很好的建议。

现在demo已经与主逻辑分离
