### ISSUE TITLE
不要用for..in来循环数组

### ISSUE THREAD

**Issue by chiikin** [mengshukeji/Luckyexcel#37]
在我们的项目中总会有各种各样的封装，包括给数组增加适合我们业务的扩展方法，但是代码中的for...in给我的项目带来的大麻烦，致使无法正常使用luckyexcel，我们也不希望放弃项目中的扩展方法因此

希望不要在项目中使用for...in来循环数组

**Comment by Dushusir** [comment]
> 在我们的项目中总会有各种各样的封装，包括给数组增加适合我们业务的扩展方法，但是代码中的for...in给我的项目带来的大麻烦，致使无法正常使用luckyexcel，我们也不希望放弃项目中的扩展方法因此
> 
> 希望不要在项目中使用for...in来循环数组

明白，for in 一般用于对象循环。

如果可能的话，请帮助我们直接更正，或者指出具体哪些地方有问题。非常感谢提出建议。
