### ISSUE TITLE
行首多个空格会变为一个

### ISSUE THREAD

**Issue by SuyongSun** [mengshukeji/Luckyexcel#4]
xlsx中编辑的文字，如果单元格内的文字前面有空格（多是段落起始空两格类似的情况），多个空格导入后在显示上只有一个，但进入编辑状态，实际有多个空格。
另外一个问题，将提在luckyexcel，这里简要描述下，就是单无格内的文字编辑，如果不是在文字尾部，在头部或中间任意位置编辑，输入一个字符后，光标就会跳到文字尾部，无法连续在头部或中间输入文字。

**Comment by wbfsa** [comment]
这个问题还在不在？

**Comment by SuyongSun** [comment]
> 这个问题还在不在？

目前导入行首空格都有保留，正常。
