### ISSUE TITLE
打包完没有出现文档中的boundle.js

### ISSUE THREAD

**Issue by 1025431504** [mengshukeji/Luckyexcel#9]
![image](https://user-images.githubusercontent.com/48747641/96825390-917ae400-1463-11eb-81aa-bef8adbe5774.png)
![image](https://user-images.githubusercontent.com/48747641/96825399-99d31f00-1463-11eb-8e01-205d37849a6a.png)
如何处理

**Comment by Jiji-Jiong** [comment]
![sheet导入](https://user-images.githubusercontent.com/67767757/98077658-9b610600-1eab-11eb-888f-62f018687589.png)

用这个

**Comment by 1025431504** [comment]
@Jiji-Jiong  好的 我试试康康

**Comment by 1025431504** [comment]
@Jiji-Jiong 好的 我试试看看

**Comment by mengshukeji** [comment]
打包现已支持 Commonjs/ES/UMD规范
